#ifndef NX_USER_H
#define NX_USER_H

#define NX_ENABLE_INTERFACE_CAPABILITY
#define NX_DISABLE_IPV6
#define NX_TCP_MAX_OUT_OF_ORDER_PACKETS 8
#define NX_DHCP_CLIENT_RESTORE_STATE
#define NX_ENABLE_VLAN

#endif